# go.yml
_format_version: "1.1"
services:
- url: https://reqres.in
  routes:
  - paths:
    - "/req"
  plugins:
  - name: custom-auth

- url: https://jsonplaceholder.typicode.com
  routes:
  - paths:
    - "/typicode"
  plugins:
  - name: api-key
    config:
      apikey: cxt