version: "2"
services:
  kong-go-svc:
    build: .
    environment:
      - KONG_DATABASE=off
      - KONG_GO_PLUGINS_DIR=/tmp/go-plugins
      - KONG_DECLARATIVE_CONFIG=/tmp/config.yml
      - KONG_PLUGINS=custom-auth,api-key
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net  
networks:
    kong-net:
        external: true      